name: satisfactory

services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    hostname: satisfactory-server
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    environment:
      - MAXPLAYERS=4
      - PGID=100
      - PUID=2001
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    networks:
      - private-satisfactory
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
  
  satisfactory-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'satisfactory-monitor'
    environment:
      - RESTART_SCHEDULE=4:30
      - MANAGE_SERVICES=satisfactory-server
      - DOCKER_COMPOSE_PATH=${PWD}
      # PWD is not set in the container by default. We need to pass it in
      # from the host so that it's available when Compose processes the
      # docker-compose.yml file when restarting or updating services.
      - PWD=${PWD}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ${PWD}:${PWD}
    restart: always
    command: index.js
    networks:
      - private-satisfactory
networks:
  private-satisfactory: